{% set name = "deferrer" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/deferrer-{{ version }}.tar.gz
  sha256: 5dc87882b6bdaac1eb1ae39155f62f4a47a168f3fd8c460c96bcc3347c2f38ab

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python >=3.11 <3.15

test:
  imports:
    - deferrer
  commands:
    - pip check
  requires:
    - python >=3.11 <3.15
    - pip

about:
  home: https://github.com/Azureblade3808/py-deferrer
  summary: Fancy `defer` for Python >= 3.12 (partially supported in Python 3.11)
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Azureblade3808
